#!/usr/bin/env zsh
set -e

daemon=$(git config --get emacs.daemon)
emacsclient=(${(A)$(/usr/bin/type -ap emacsclient)})
if [[ -n "$daemon" ]]; then
  exec $emacsclient[2] --alternate-editor= -s "$daemon" "$@"
else
  exec $emacsclient[2] "$@"
fi
